version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - '**/*'