version: 0.2
env:
  variables:
    FLASK_APP: "run.py"
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - python -m flask run
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'