version: 0.2
env:
  variables:
    FLASK_APP = run.py
phases:
  install:
    runtime-versions:
      python: 3.7
    pre_build:
      commands:
        - echo Entered the pre_build phase...
        - pip install -r requirements.txt
        - pip install -e .
      build:
        - python -m flask run
      artifacts:
        files:
          - '**/*'